# Tutorial Pandas - Parte 2
## Por Germano Yoneda

- Removendo linhas e colunas
- Renomeando colunas
- Funções principais(map)
- Preenchendo valores nulos (NaN)
- Agrupando e ordenando
- Renomeando colunas e índices (maneira Nº2)

In [1]:
#pip install pandas

In [46]:
import pandas as pd

# Removendo Linhas e Colunas!

In [47]:
wine = pd.read_csv('https://raw.githubusercontent.com/Haller-x/LinkedData/master/Tutorial%20Pandas/wine_modificado.csv')

In [48]:
wine_teste = wine.copy()

In [49]:
wine_teste.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt

In [50]:
wine_teste.drop([0,1,2,3],axis=0,inplace=True)

In [51]:
wine_teste.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,Bom,5,44.0,1594,Spain,Northern Spain,Michael Schachner
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,Bom,5,29.0,1593,Italy,Sicily & Sardinia,Kerin O’Keefe
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,Excelente,7,34.0,1592,France,Alsace,Roger Voss
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,Excelente,7,35.0,1591,Germany,Rheinhessen,Anna Lee C. Iijima

In [52]:
#OU
#wine_teste= wine_teste.drop([0,1,2,3],axis=0)

In [53]:
wine_teste.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,Bom,5,44.0,1594,Spain,Northern Spain,Michael Schachner
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,Bom,5,29.0,1593,Italy,Sicily & Sardinia,Kerin O’Keefe
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,Excelente,7,34.0,1592,France,Alsace,Roger Voss
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,Excelente,7,35.0,1591,Germany,Rheinhessen,Anna Lee C. Iijima

In [54]:
wine_teste.drop('índice invertido',axis=1, inplace=True)

In [55]:
wine_teste.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,country,province,taster_name
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,US,Oregon,Paul Gregutt
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,Bom,5,44.0,Spain,Northern Spain,Michael Schachner
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,Bom,5,29.0,Italy,Sicily & Sardinia,Kerin O’Keefe
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,Excelente,7,34.0,France,Alsace,Roger Voss
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,Excelente,7,35.0,Germany,Rheinhessen,Anna Lee C. Iijima

# Renomeando colunas

Para renomear colunas é bem simples, basta criar uma lista de elementos que tenha o mesmo número de elementos que o número de colunas e atribuir diretamente ao `.columns`

In [56]:
wine_teste.columns = [i for i in range(17)]
wine_teste.head(2)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
4,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,US,Oregon,Paul Gregutt
5,7.4,0.66,0.0,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,Bom,5,44.0,Spain,Northern Spain,Michael Schachner

# Funções
<h3>Introdução</h3>
No último tutorial nós aprendemos como selecionar dados relevantes no DataFrame ou numa Série. Obtendo os dados na representação correta é algo crucial para realizar o trabalho, como nós mostraremos nos exercícios.

Entretanto, o dados nem vem sempre na forma que queremos de cara. Ás vezes nós precisamos de algum trabalho adicional para formatar os dados da maneira correta. Este tutorial abordará algumas operações que podem ser aplicadas aos dados.

Funções “de resumo”
O pandas vem naturalmente com algumas funções que reestruturam os dados de uma maneira útil. Por exemplo:
O método .describe():

In [57]:
wine.country.describe()

count     1598
unique      19
top         US
freq       629
Name: country, dtype: object

In [58]:
wine.price.describe()

count    1589.000000
mean       25.326621
std        14.509952
min         1.000000
25%        12.000000
50%        26.000000
75%        38.000000
max        50.000000
Name: price, dtype: float64

Este método gera um resumo de alto nível dos atributos da coluna dada,  reconhece o tipo de dados, sendo que alguns dados só fazem sentido para dados numéricos.

Se você quiser algum resumo de um método em particular de uma coluna pode-se usar algo parecido com:

In [59]:
wine.price.mean()

25.32662051604783

Para vermos uma lista de valores únicos podemos usar a função.unique()

In [60]:
wine.price.unique()

array([39., 40., 24., 44., 29., 34., 35., 27., 13., 43., 38., 19., 30.,
        2., 15.,  1., 16., 31., 45., 42., 48.,  9., 14., 10., 32.,  7.,
        8., 46.,  5., 41., 26., 25., 23., 33., 49., 11., 22., 20., 36.,
       18., 12.,  4., 47., 21., 37., 28.,  3., 50.,  6., 17., nan])

Para vermos uma lista de valores exclusivos e com que frequência ocorrem no conjunto, podemos usar o método value_counts()

In [61]:
wine.price.value_counts()

43.0    48
4.0     46
29.0    41
8.0     41
48.0    40
30.0    39
46.0    38
11.0    36
1.0     36
21.0    35
7.0     35
35.0    35
31.0    34
45.0    34
37.0    34
25.0    34
5.0     33
16.0    33
9.0     33
15.0    32
17.0    32
32.0    32
12.0    32
3.0     32
49.0    32
20.0    32
41.0    31
40.0    31
14.0    31
33.0    31
13.0    31
38.0    31
44.0    30
39.0    30
42.0    30
19.0    29
28.0    29
36.0    28
10.0    28
34.0    28
22.0    27
27.0    27
6.0     27
26.0    26
18.0    25
23.0    25
47.0    24
24.0    24
2.0     22
50.0    15
Name: price, dtype: int64

# Avaliando dados nulos e preenchendo com o próximo valor da coluna (não nulo)

In [62]:
wine.isnull().sum()

fixed acidity             0
volatile acidity          0
citric acid               0
residual sugar            0
chlorides                 0
free sulfur dioxide       0
total sulfur dioxide      0
density                   0
pH                        0
sulphates                 0
alcohol                   0
label                     0
quality                   0
price                    10
índice invertido          0
country                   1
province                  1
taster_name             307
dtype: int64

In [63]:
wine.price.ffill(inplace=True)

# Função Maps
”Map” é um termo, emprestado da matemática, para uma função que pega um conjunto de valores e os “mapeia” para um novo conjunto de valores. Na ciência de dados, geralmente precisamos alterar a representação dos dados, o método maps pode ser uma ferramenta extremamente útil para isso.
    
Existem dois tipos de “mapeamento” que usaremos com frequência. map() é um pouco mais simples, vamos supor que desejássemos reorganizar a o preço dos vinhos. Podemos fazer isso da seguinte maneira:

In [64]:
wine_price_mean = wine.price.mean()
wine.price.map(lambda p: (p - wine_price_mean))

0       13.602877
1       13.602877
2       13.602877
3       14.602877
4       -1.397123
          ...
1594     0.602877
1595   -18.397123
1596    19.602877
1597    13.602877
1598    22.602877
Name: price, Length: 1599, dtype: float64

In [65]:
#Note que não houve modificação no DataFrame
wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt

A função que você passa para o método map() é aplicada a todos os valores da Série e retorna uma nova série com os dados transformados. 

O método apply() é equivalente se quisermos transformar um DataFrame inteiro chamando um método personalizado a cada linha.

In [66]:
def remean_price(df):
    df.price = df.price - wine_price_mean
    return df
wine.apply(remean_price, axis='columns')

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,13.602877,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Bom,5,13.602877,1598,Portugal,Douro,Roger Voss
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Bom,5,13.602877,1597,US,Oregon,Paul Gregutt
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Muito bom,6,14.602877,1596,US,Michigan,Alexander Peartree
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,-1.397123,1595,US,Oregon,Paul Gregutt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,Bom,5,0.602877,5,France,Bordeaux,Roger Voss
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,Muito bom,6,-18.397123,4,France,Bordeaux,Roger Voss
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,Muito bom,6,19.602877,3,France,Bordeaux,Roger Voss
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,Bom,5,13.602877,2,France,Bordeaux,Roger Voss
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,Muito bom,6,22.602877,1,US,Washington,Sean P. Sullivan

Se nós tivéssemos chamado wine.apply() com axis=’index’, então teríamos passado uma função para transformar cada linha, nós precisamos dar uma função para transformar cada coluna.

Note que tanto map() e apply() retornam novas Series e DataFrames, não modificando os originais.

A biblioteca pandas permite muitas opções de “mapeamento” já embutidas, por exemplo, aqui temos uma maneira mais simples para remanejar os itens das colunas:

In [67]:
wine_price_mean = wine.price.mean()
wine.price - wine_price_mean

0       13.602877
1       13.602877
2       13.602877
3       14.602877
4       -1.397123
          ...
1594     0.602877
1595   -18.397123
1596    19.602877
1597    13.602877
1598    22.602877
Name: price, Length: 1599, dtype: float64

Nesse código nós estamos performando uma operação entre muitos valores, do lado esquerdo temos o número da operação e do lado direito temos o “valor médio”. A biblioteca pandas olha para a expressão e entende que devemos subtrair a média dos valores, para cada valor no conjunto de dados.

Pandas também entenderá o que ele deve fazer entre operações quando as Séries apresentam o mesmo comprimento. Por exemplo, uma maneira fácil de combinar o label e a provincia seria:

In [68]:
wine.label.apply(str) + " - " + wine.province.apply(str)

0       Bom - Sicily & Sardinia
1                   Bom - Douro
2                  Bom - Oregon
3          Muito bom - Michigan
4                  Bom - Oregon
                 ...
1594             Bom - Bordeaux
1595       Muito bom - Bordeaux
1596       Muito bom - Bordeaux
1597             Bom - Bordeaux
1598     Muito bom - Washington
Length: 1599, dtype: object

Esses operadores são mais rápido do que os métodos map() ou apply() porque eles já têm acelerações embutidas no pandas. Todos os operadores padrões (nativos do python) funcionam dessa maneira.

Entretanto, esses operadores não são tão flexíveis quanto map() e apply(), os quais podem ser usados para fazer coisas mais avançadas, como aplicar condicionais, que não podem ser realizadas adições e subtrações sozinhas.

# Agrupando e classificando
<h3>Introdução</h3>
O “mapeamento” permite que transformemos os dados de um DataFrame ou uma Série um a um para uma coluna inteira. Entretanto, em muitos casos precisamos agrupar os dados, e então fazer alguma coisa com o grupo que os dados estão.

Assim como você aprenderá, nós faremos isso utilizando a operação groupby(). Nós também iremos cobrir alguns tópicos adicionais, como formas mais complexas de indexar seus DataFrames, além de como classificar seus dados.

<h3>Análise de grupo</h3>
	Uma função que nós temos usado de maneira frequente é a value_counts(). Nós podemos replicar o que value_counts() faz usando o seguinte:

In [69]:
wine.groupby('price').price.count()

price
1.0     36
2.0     22
3.0     32
4.0     46
5.0     33
6.0     27
7.0     35
8.0     42
9.0     33
10.0    28
11.0    36
12.0    32
13.0    31
14.0    31
15.0    32
16.0    33
17.0    32
18.0    25
19.0    29
20.0    32
21.0    35
22.0    27
23.0    25
24.0    24
25.0    34
26.0    26
27.0    27
28.0    29
29.0    42
30.0    39
31.0    34
32.0    33
33.0    31
34.0    29
35.0    35
36.0    29
37.0    34
38.0    31
39.0    30
40.0    31
41.0    31
42.0    31
43.0    49
44.0    31
45.0    34
46.0    38
47.0    24
48.0    41
49.0    32
50.0    16
Name: price, dtype: int64

groupby() criou um grupo das wine que atribuiu os mesmos valores em pontos aos vinhos indicados. 

Então, para cada um desses grupos, nós contamos quantas vezes ela apareceu. value_counts() é apenas um atalho para esta operação groupby().

Nós podemos usar qualquer uma das funções de resumo que nós já usamos com esses dados. Por exemplo, para pegar o vinho mais barato em cada país, nós podemos fazer o seguinte:

In [70]:
wine.groupby('country').price.min()

country
Argentina        1.0
Australia        1.0
Austria          1.0
Canada          42.0
Chile            2.0
France           1.0
Germany          1.0
Greece           4.0
Hungary         20.0
Israel           1.0
Italy            1.0
Mexico           4.0
New Zealand      2.0
Portugal         1.0
Romania          9.0
South Africa     3.0
Spain            1.0
Turkey           7.0
US               1.0
Name: price, dtype: float64

Você pode pensar em cada grupo que geramos como uma fatia do nosso DataFrame contendo apenas dados com valores correspondentes. Esse DataFrame pode ser acessado diretamente por nós utilizando o método apply(), e podemos manipular os dados da maneira que acharmos melhor.

Por exemplo, aqui temos um exemplo de uma maneira de obter a quantidade de classificações feitas por cada revisor

In [71]:
pd.DataFrame(wine.groupby('taster_name').apply(lambda df: df.quality.value_counts()))

                      quality
taster_name
Alexander Peartree 6        4
                   5        4
                   8        1
                   7        1
                   4        1
...                       ...
Virginie Boone     6       57
                   7       20
                   4        4
                   3        2
                   8        1

[74 rows x 1 columns]

Para cada controle ainda mais refinado você também pode agrupar por mais de uma coluna, por exemplo, eis como escolheríamos o melhor vinho (maior qualidade) por país e província.

In [72]:
wine.groupby(['country', 'province']).apply(lambda df: df.loc[df.quality.idxmax()])

                            fixed acidity  volatile acidity  citric acid  \
country   province
Argentina Mendoza Province            8.0              0.38         0.06
          Other                       8.5              0.28         0.56
Australia Australia Other             8.2              0.34         0.38
          South Australia             5.6              0.66         0.00
          Tasmania                    8.8              0.59         0.18
...                                   ...               ...          ...
US        Oregon                     10.3              0.32         0.45
          Pennsylvania                7.5              0.58         0.56
          Texas                       8.6              0.42         0.39
          Virginia                    7.9              0.32         0.51
          Washington                 12.6              0.31         0.72

                            residual sugar  chlorides  free sulfur dioxide  \
country   province
Argentina Mendoza Province             1.8      0.078                 12.0
          Other                        1.8      0.092                 35.0
Australia Australia Other              2.5      0.080                 12.0
          South Australia              2.2      0.087                  3.0
          Tasmania                     2.9      0.089                 12.0
...                                    ...        ...                  ...
US        Oregon                       6.4      0.073                  5.0
          Pennsylvania                 3.1      0.153                  5.0
          Texas                        1.8      0.068                  6.0
          Virginia                     1.8      0.341                 17.0
          Washington                   2.2      0.072                  6.0

                            total sulfur dioxide  density    pH  sulphates  \
country   province
Argentina Mendoza Province                  49.0  0.99625  3.37       0.52
          Other                            103.0  0.99690  3.30       0.75
Australia Australia Other                   57.0  0.99780  3.30       0.47
          South Australia                   11.0  0.99378  3.71       0.63
          Tasmania                          74.0  0.99738  3.14       0.54
...                                          ...      ...   ...        ...
US        Oregon                            13.0  0.99760  3.23       0.82
          Pennsylvania                      14.0  0.99476  3.21       1.03
          Texas                             12.0  0.99516  3.35       0.69
          Virginia                          56.0  0.99690  3.04       1.08
          Washington                        29.0  0.99870  2.88       0.82

                            alcohol        label  quality  price  \
country   province
Argentina Mendoza Province      9.9    Muito bom        6    4.0
          Other                10.5    Excelente        7    2.0
Australia Australia Other       9.0    Muito bom        6    1.0
          South Australia      12.8    Excelente        7   42.0
          Tasmania              9.4          Bom        5   49.0
...                             ...          ...      ...    ...
US        Oregon               12.6  Excepcional        8    6.0
          Pennsylvania         11.6    Muito bom        6    6.0
          Texas                11.7  Excepcional        8   30.0
          Virginia              9.2    Muito bom        6   19.0
          Washington            9.8  Excepcional        8   48.0

                            índice invertido    country          province  \
country   province
Argentina Mendoza Province              1368  Argentina  Mendoza Province
          Other                         1583  Argentina             Other
Australia Australia Other                853  Australia   Australia Other
          South Australia                602  Australia   South Australia
          Tasmania                       833  Australia          Tasmania
...                                      ...        ...               ...
US        Oregon                        1321         US            Oregon
          Pennsylvania                   228         US      Pennsylvania
          Texas                          397         US             Texas
          Virginia                      1580         US          Virginia
          Washington                    1159         US        Washington

                                   taster_name
country   province
Argentina Mendoza Province   Michael Schachner
          Other              Michael Schachner
Australia Australia Other       Joe Czerwinski
          South Australia       Joe Czerwinski
          Tasmania              Joe Czerwinski
...                                        ...
US        Oregon                  Paul Gregutt
          Pennsylvania         Susan Kostrzewa
          Texas             Alexander Peartree
          Virginia          Alexander Peartree
          Washington          Sean P. Sullivan

[121 rows x 18 columns]

# Tipos de dados e valores faltantes
<h3>Tipos de dados</h3>

Às vezes o tipo de determinado dado não é adequado, para isso devemos modificar seu tipo. No Pandas tempos a função dtype() que fornece o tipo de dado.

Utilizando o exemplo dos vinhos, se quisermos obter o tipo de dados de todas as colunas podemos utilizar:

In [73]:
wine.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
label                    object
quality                   int64
price                   float64
índice invertido          int64
country                  object
province                 object
taster_name              object
dtype: object

Caso queiramos obter apenas o tipo de dado de dada coluna:

In [74]:
wine.price.dtype

dtype('float64')

Note que valores do tipo inteiro são classificados como int64, valores do tipo ponto flutuante são classificados como float64, e strings são classificadas como objects!

Caso faça sentido para o Pandas, pode-se alterar o tipo de dado utilizando o método astype. Por exemplo:

In [75]:
wine.price.astype('int64')

0       39
1       39
2       39
3       40
4       24
        ..
1594    26
1595     7
1596    45
1597    39
1598    48
Name: price, Length: 1599, dtype: int64

#Valores Faltantes
	
Dados faltantes são encontrados nos DataFrames e Series como NaN (not a number), um dado do tipo float64. Podemos buscar itens com NaN, assim como buscar itens onde NaN’s não estão presentes:

Para buscar valores nulos:

In [76]:
wine[pd.isnull(wine.country)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
913,9.4,0.395,0.46,4.6,0.094,3.0,10.0,0.99639,3.27,0.64,12.2,Excelente,7,26.0,686,NaN,NaN,Mike DeSimone

Para buscar valores não-nulos:

In [77]:
wine[pd.notnull(wine.country)]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,Bom,5,26.0,5,France,Bordeaux,Roger Voss
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,Muito bom,6,7.0,4,France,Bordeaux,Roger Voss
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,Muito bom,6,45.0,3,France,Bordeaux,Roger Voss
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,Bom,5,39.0,2,France,Bordeaux,Roger Voss
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,Muito bom,6,48.0,1,US,Washington,Sean P. Sullivan

Preenchendo valores NaN com Unknown:

In [78]:
wine.country.isnull().sum()

1

In [79]:
wine.country.fillna('Unknown',inplace=True)
wine.province.fillna('Unknown',inplace=True)

In [80]:
wine.country.isnull().sum()

0

# Ordenando!

In [81]:
wine.sort_values(by='price',ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
1062,8.0,0.380,0.44,1.9,0.098,6.0,15.0,0.99560,3.30,0.64,11.4,Muito bom,6,50.0,537,Italy,Northeastern Italy,NaN
353,13.5,0.530,0.79,4.8,0.120,23.0,77.0,1.00180,3.18,0.77,13.0,Bom,5,50.0,1246,France,Burgundy,Roger Voss
1517,6.5,0.530,0.06,2.0,0.063,29.0,44.0,0.99489,3.38,0.83,10.3,Muito bom,6,50.0,82,France,Southwest France,Roger Voss
1075,9.1,0.250,0.34,2.0,0.071,45.0,67.0,0.99769,3.44,0.86,10.2,Excelente,7,50.0,524,US,California,Virginie Boone
1016,8.9,0.380,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.6,Excelente,7,50.0,583,Italy,Sicily & Sardinia,Kerin O’Keefe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,8.1,0.545,0.18,1.9,0.080,13.0,35.0,0.99720,3.30,0.59,9.0,Muito bom,6,1.0,1497,US,New York,Anna Lee C. Iijima
1052,5.6,0.605,0.05,2.4,0.073,19.0,25.0,0.99258,3.56,0.55,12.9,Bom,5,1.0,547,US,California,NaN
1550,7.1,0.680,0.00,2.3,0.087,17.0,26.0,0.99783,3.45,0.53,9.5,Bom,5,1.0,49,Italy,Veneto,Kerin O’Keefe
472,12.5,0.370,0.55,2.6,0.083,25.0,68.0,0.99950,3.15,0.82,10.4,Muito bom,6,1.0,1127,France,Burgundy,Roger Voss
1295,6.6,0.630,0.00,4.3,0.093,51.0,77.5,0.99558,3.20,0.45,9.5,Bom,5,1.0,304,US,California,Matt Kettmann

In [82]:
wine.sort_values(by=['price','quality'],ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
243,15.0,0.210,0.44,2.2,0.075,10.0,24.0,1.00005,3.07,0.84,9.2,Excelente,7,50.0,1356,US,New York,NaN
1016,8.9,0.380,0.40,2.2,0.068,12.0,28.0,0.99486,3.27,0.75,12.6,Excelente,7,50.0,583,Italy,Sicily & Sardinia,Kerin O’Keefe
1029,7.7,0.580,0.01,1.8,0.088,12.0,18.0,0.99568,3.32,0.56,10.5,Excelente,7,50.0,570,Spain,Northern Spain,Michael Schachner
1075,9.1,0.250,0.34,2.0,0.071,45.0,67.0,0.99769,3.44,0.86,10.2,Excelente,7,50.0,524,US,California,Virginie Boone
780,7.0,0.570,0.00,2.0,0.190,12.0,45.0,0.99676,3.31,0.60,9.4,Muito bom,6,50.0,819,Italy,Tuscany,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,8.2,0.280,0.60,3.0,0.104,10.0,22.0,0.99828,3.39,0.68,10.6,Bom,5,1.0,118,US,California,NaN
1485,7.0,0.655,0.16,2.1,0.074,8.0,25.0,0.99606,3.37,0.55,9.7,Bom,5,1.0,114,US,California,NaN
1550,7.1,0.680,0.00,2.3,0.087,17.0,26.0,0.99783,3.45,0.53,9.5,Bom,5,1.0,49,Italy,Veneto,Kerin O’Keefe
18,7.4,0.590,0.08,4.4,0.086,6.0,29.0,0.99740,3.38,0.50,9.0,Regular,4,1.0,1581,Spain,Northern Spain,Michael Schachner
266,8.1,0.870,0.00,3.3,0.096,26.0,61.0,1.00025,3.60,0.72,9.8,Regular,4,1.0,1333,Argentina,Mendoza Province,Michael Schachner

In [83]:
wine.sort_values(by=['quality','price'],ascending=False)#Note a ordem de prioridade!

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
440,12.6,0.31,0.72,2.2,0.072,6.0,29.0,0.99870,2.88,0.82,9.80,Excepcional,8,48.0,1159,US,Washington,Sean P. Sullivan
1449,7.2,0.38,0.31,2.0,0.056,15.0,29.0,0.99472,3.23,0.76,11.30,Excepcional,8,45.0,150,France,Rhône Valley,Joe Czerwinski
498,10.7,0.35,0.53,2.6,0.070,5.0,16.0,0.99720,3.15,0.65,11.00,Excepcional,8,39.0,1101,US,California,NaN
1549,7.4,0.36,0.30,1.8,0.074,17.0,24.0,0.99419,3.24,0.70,11.40,Excepcional,8,35.0,50,Chile,Central Valley,Michael Schachner
1202,8.6,0.42,0.39,1.8,0.068,6.0,12.0,0.99516,3.35,0.69,11.70,Excepcional,8,30.0,397,US,Texas,Alexander Peartree
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469,7.3,0.98,0.05,2.1,0.061,20.0,49.0,0.99705,3.31,0.55,9.70,Péssimo,3,19.0,130,US,California,Virginie Boone
1505,6.7,0.76,0.02,1.8,0.078,6.0,12.0,0.99600,3.55,0.63,9.95,Péssimo,3,17.0,94,Austria,Kamptal,Roger Voss
899,8.3,1.02,0.02,3.4,0.084,6.0,11.0,0.99892,3.48,0.49,11.00,Péssimo,3,12.0,700,Italy,Tuscany,NaN
832,10.4,0.44,0.42,1.5,0.145,34.0,48.0,0.99832,3.38,0.86,9.90,Péssimo,3,7.0,767,France,Beaujolais,Roger Voss
517,10.4,0.61,0.49,2.1,0.200,5.0,16.0,0.99940,3.16,0.63,8.40,Péssimo,3,5.0,1082,US,California,Virginie Boone

In [84]:
wine.sort_index(ascending=False)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,Muito bom,6,48.0,1,US,Washington,Sean P. Sullivan
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,Bom,5,39.0,2,France,Bordeaux,Roger Voss
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,Muito bom,6,45.0,3,France,Bordeaux,Roger Voss
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,Muito bom,6,7.0,4,France,Bordeaux,Roger Voss
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,Bom,5,26.0,5,France,Bordeaux,Roger Voss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe

# Renomeando
<h3>Introdução</h3>

Algumas vezes os dados vêm com nomes de colunas ou índices que podem ser confusas ou difíceis de trabalhar. Para isso o pandas conta com alguns métodos que permitem a renomeação de colunas e índices.
Renomeando

O método rename()  permite a modificação dos nomes das colunas e dos índices (rótulos). Por exemplo, para modificar a coluna price por score:

In [85]:
wine.rename(columns={'price':'preço'})

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,preço,índice invertido,country,province,taster_name
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,Bom,5,26.0,5,France,Bordeaux,Roger Voss
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,Muito bom,6,7.0,4,France,Bordeaux,Roger Voss
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,Muito bom,6,45.0,3,France,Bordeaux,Roger Voss
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,Bom,5,39.0,2,France,Bordeaux,Roger Voss
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,Muito bom,6,48.0,1,US,Washington,Sean P. Sullivan

Para modificar os índices:

In [86]:
wine.rename(index={0:'index0',1:'index1'})

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,label,quality,price,índice invertido,country,province,taster_name
index0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,39.0,1599,Italy,Sicily & Sardinia,Kerin O’Keefe
index1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,Bom,5,39.0,1598,Portugal,Douro,Roger Voss
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,Bom,5,39.0,1597,US,Oregon,Paul Gregutt
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,Muito bom,6,40.0,1596,US,Michigan,Alexander Peartree
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,Bom,5,24.0,1595,US,Oregon,Paul Gregutt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,Bom,5,26.0,5,France,Bordeaux,Roger Voss
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,Muito bom,6,7.0,4,France,Bordeaux,Roger Voss
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,Muito bom,6,45.0,3,France,Bordeaux,Roger Voss
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,Bom,5,39.0,2,France,Bordeaux,Roger Voss
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,Muito bom,6,48.0,1,US,Washington,Sean P. Sullivan

Renomear colunas é algo bem comum, já renomear índices não tanto, por isso em grande parte das vezes é mais conveniente usar o método  set_index().

Tanto os índices das linhas como os das colunas podem ter seu próprio atributo nome. O método rename_axis() pode ser utilizado para modificar esses nomes.